// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: KitsuDeck

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Navbar;
lv_obj_t * ui_Clock;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_ImgButton3;
void ui_event_SettingsBtn(lv_event_t * e);
lv_obj_t * ui_SettingsBtn;
lv_obj_t * ui_DeckCol;
lv_obj_t * ui_DeckMacroNav;

// SCREEN: ui_SettingsView
void ui_SettingsView_screen_init(void);
void ui_event_SettingsView(lv_event_t * e);
lv_obj_t * ui_SettingsView;
void ui_event_SettingsHeaderPanel(lv_event_t * e);
lv_obj_t * ui_SettingsHeaderPanel;
void ui_event_SettingsBackToHome(lv_event_t * e);
lv_obj_t * ui_SettingsBackToHome;
lv_obj_t * ui_SettingsHeader;
void ui_event_SettingsPanel(lv_event_t * e);
lv_obj_t * ui_SettingsPanel;
void ui_event_WifiConnect(lv_event_t * e);
lv_obj_t * ui_WifiConnect;
lv_obj_t * ui_WifiHeader;
lv_obj_t * ui_WifiSsidRoller;
void ui_event_WifiPasswordTextInput(lv_event_t * e);
lv_obj_t * ui_WifiPasswordTextInput;
lv_obj_t * ui_ButtonPanel;
void ui_event_WifiScanButton(lv_event_t * e);
lv_obj_t * ui_WifiScanButton;
lv_obj_t * ui_WifiScanText;
void ui_event_WifiSaveButton(lv_event_t * e);
lv_obj_t * ui_WifiSaveButton;
lv_obj_t * ui_WifiSaveText;
lv_obj_t * ui_WifiTestResultLabel;
lv_obj_t * ui_ButtonPanel2;
void ui_event_TestWifiSettingsButton(lv_event_t * e);
lv_obj_t * ui_TestWifiSettingsButton;
lv_obj_t * ui_TestWifiSettingsText;
void ui_event_ComputerSettings(lv_event_t * e);
lv_obj_t * ui_ComputerSettings;
lv_obj_t * ui_ComputerSettingsHeader;
lv_obj_t * ui_AuthStatus;
void ui_event_ComputerAuthPin(lv_event_t * e);
lv_obj_t * ui_ComputerAuthPin;
void ui_event_ComputerAuthPinNew(lv_event_t * e);
lv_obj_t * ui_ComputerAuthPinNew;
void ui_event_ComputerSaveButton(lv_event_t * e);
lv_obj_t * ui_ComputerSaveButton;
lv_obj_t * ui_ComputerSaveText;
void ui_event_DeviceSettings(lv_event_t * e);
lv_obj_t * ui_DeviceSettings;
lv_obj_t * ui_DeviceSettingsHeader;
lv_obj_t * ui_Label2;
void ui_event_ScreenBrightnessArk(lv_event_t * e);
lv_obj_t * ui_ScreenBrightnessArk;
void ui_event_DeviceInformation(lv_event_t * e);
lv_obj_t * ui_DeviceInformation;
lv_obj_t * ui_DeviceInformationHeader;
lv_obj_t * ui_KitsuDeckVersion;
lv_obj_t * ui_RamHeader;
lv_obj_t * ui_RamValue;
lv_obj_t * ui_PsramHeader;
lv_obj_t * ui_PsramValue;
lv_obj_t * ui_CreatedByInformation;
lv_obj_t * ui_SettingsKeyboardText;
lv_obj_t * ui_SettingsKeyboardNumber;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_b[1] = {&ui_img_b2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initHome(e);
    }
}
void ui_event_SettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_SettingsView, LV_SCR_LOAD_ANIM_NONE, 500, 0);
    }
}
void ui_event_SettingsView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initSettings(e);
    }
}
void ui_event_SettingsHeaderPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SettingsBackToHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0);
    }
}
void ui_event_SettingsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_WifiConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_WifiPasswordTextInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_SettingsKeyboardText,  ui_WifiPasswordTextInput);
    }
}
void ui_event_WifiScanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        ScanWifiSsid(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_WifiSaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        SaveWifiSettings(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TestWifiSettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        TestWifiSettings(e);
    }
}
void ui_event_ComputerSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ComputerAuthPin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_SettingsKeyboardNumber,  ui_ComputerAuthPin);
    }
}
void ui_event_ComputerAuthPinNew(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_SettingsKeyboardNumber,  ui_ComputerAuthPinNew);
    }
}
void ui_event_ComputerSaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        SaveComputerAuthSettings(e);
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_DeviceSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ScreenBrightnessArk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setSettingsBrightnessArkValue(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        saveSettingsBrightnessArkValue(e);
    }
}
void ui_event_DeviceInformation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_SettingsView_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
