// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: KitsuDeck

#include "../ui.h"

void ui_SettingsView_screen_init(void)
{
ui_SettingsView = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_SettingsView,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsView, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_SettingsView, lv_color_hex(0x0B0D10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsView, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SettingsView, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsView, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsView, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsView, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsHeaderPanel = lv_obj_create(ui_SettingsView);
lv_obj_set_width( ui_SettingsHeaderPanel, lv_pct(100));
lv_obj_set_height( ui_SettingsHeaderPanel, lv_pct(13));
lv_obj_set_align( ui_SettingsHeaderPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsHeaderPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsHeaderPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsHeaderPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingsHeaderPanel, lv_color_hex(0x0B0D10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsHeaderPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SettingsHeaderPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SettingsHeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsHeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsHeaderPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsHeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsBackToHome = lv_imgbtn_create(ui_SettingsHeaderPanel);
lv_imgbtn_set_src(ui_SettingsBackToHome, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_b2_png, NULL);
lv_imgbtn_set_src(ui_SettingsBackToHome, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_b2_png, NULL);
lv_obj_set_height( ui_SettingsBackToHome, 32);
lv_obj_set_width( ui_SettingsBackToHome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_SettingsBackToHome, -1 );
lv_obj_set_y( ui_SettingsBackToHome, 34 );
lv_obj_set_align( ui_SettingsBackToHome, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_SettingsBackToHome, lv_color_hex(0x101418), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_SettingsBackToHome, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_SettingsHeader = lv_label_create(ui_SettingsHeaderPanel);
lv_obj_set_width( ui_SettingsHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsHeader,"Settings");
lv_obj_set_style_text_font(ui_SettingsHeader, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsPanel = lv_obj_create(ui_SettingsView);
lv_obj_set_width( ui_SettingsPanel, lv_pct(100));
lv_obj_set_flex_grow( ui_SettingsPanel, 1);
lv_obj_set_x( ui_SettingsPanel, -383 );
lv_obj_set_y( ui_SettingsPanel, -211 );
lv_obj_set_align( ui_SettingsPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsPanel,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_SettingsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_SettingsPanel, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_SettingsPanel, LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scroll_dir(ui_SettingsPanel, LV_DIR_HOR);
lv_obj_set_style_bg_color(ui_SettingsPanel, lv_color_hex(0x0B0D10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiConnect = lv_obj_create(ui_SettingsPanel);
lv_obj_set_height( ui_WifiConnect, lv_pct(100));
lv_obj_set_width( ui_WifiConnect, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_WifiConnect, 83 );
lv_obj_set_y( ui_WifiConnect, -1081 );
lv_obj_set_align( ui_WifiConnect, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_WifiConnect,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WifiConnect, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_WifiConnect, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiConnect, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_WifiConnect, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiHeader = lv_label_create(ui_WifiConnect);
lv_obj_set_width( ui_WifiHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiHeader,"Wifi settings:");
lv_obj_set_style_text_font(ui_WifiHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiTestResultLabel = lv_label_create(ui_WifiConnect);
lv_obj_set_width( ui_WifiTestResultLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiTestResultLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiTestResultLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiTestResultLabel,"");

ui_WifiSsidRoller = lv_roller_create(ui_WifiConnect);
lv_obj_set_width( ui_WifiSsidRoller, 200);
lv_obj_set_height( ui_WifiSsidRoller, lv_pct(45));
lv_obj_set_align( ui_WifiSsidRoller, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_WifiSsidRoller, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiSsidRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_WifiSsidRoller, lv_color_hex(0xE70004), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiSsidRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_WifiPasswordTextInput = lv_textarea_create(ui_WifiConnect);
lv_obj_set_width( ui_WifiPasswordTextInput, 200);
lv_obj_set_height( ui_WifiPasswordTextInput, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiPasswordTextInput, -45 );
lv_obj_set_y( ui_WifiPasswordTextInput, 2 );
lv_obj_set_align( ui_WifiPasswordTextInput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_WifiPasswordTextInput,"Password");
lv_textarea_set_one_line(ui_WifiPasswordTextInput,true);
lv_textarea_set_password_mode(ui_WifiPasswordTextInput, true);
lv_obj_set_style_bg_color(ui_WifiPasswordTextInput, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiPasswordTextInput, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ButtonPanel = lv_obj_create(ui_WifiConnect);
lv_obj_set_width( ui_ButtonPanel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_ButtonPanel, LV_SIZE_CONTENT);   /// 15
lv_obj_set_align( ui_ButtonPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ButtonPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_ButtonPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_ButtonPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonPanel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ButtonPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ButtonPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ButtonPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ButtonPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ButtonPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiScanButton = lv_btn_create(ui_ButtonPanel);
lv_obj_set_height( ui_WifiScanButton, 40);
lv_obj_set_width( ui_WifiScanButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_WifiScanButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiScanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WifiScanButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiScanButton, lv_color_hex(0xE70004), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiScanButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiScanText = lv_label_create(ui_WifiScanButton);
lv_obj_set_width( ui_WifiScanText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiScanText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiScanText, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiScanText,"Scan");

ui_WifiSaveButton = lv_btn_create(ui_ButtonPanel);
lv_obj_set_height( ui_WifiSaveButton, 40);
lv_obj_set_width( ui_WifiSaveButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_WifiSaveButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WifiSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiSaveButton, lv_color_hex(0xE70004), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSaveText = lv_label_create(ui_WifiSaveButton);
lv_obj_set_width( ui_WifiSaveText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiSaveText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiSaveText, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiSaveText,"Save");

ui_TestWifiSettingsButton = lv_btn_create(ui_WifiConnect);
lv_obj_set_height( ui_TestWifiSettingsButton, 40);
lv_obj_set_width( ui_TestWifiSettingsButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_TestWifiSettingsButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TestWifiSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TestWifiSettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TestWifiSettingsButton, lv_color_hex(0xE70004), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TestWifiSettingsButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TestWifiSettingsText = lv_label_create(ui_TestWifiSettingsButton);
lv_obj_set_width( ui_TestWifiSettingsText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TestWifiSettingsText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TestWifiSettingsText, LV_ALIGN_CENTER );
lv_label_set_text(ui_TestWifiSettingsText,"Test");

ui_ComputerSettings = lv_obj_create(ui_SettingsPanel);
lv_obj_set_height( ui_ComputerSettings, lv_pct(100));
lv_obj_set_width( ui_ComputerSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ComputerSettings, 48 );
lv_obj_set_y( ui_ComputerSettings, -431 );
lv_obj_set_align( ui_ComputerSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ComputerSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ComputerSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_set_style_bg_color(ui_ComputerSettings, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ComputerSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ComputerSettings, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ComputerSettingsHeader = lv_label_create(ui_ComputerSettings);
lv_obj_set_width( ui_ComputerSettingsHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ComputerSettingsHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ComputerSettingsHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_ComputerSettingsHeader,"Auth Settings:");
lv_obj_set_style_text_font(ui_ComputerSettingsHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AuthStatus = lv_label_create(ui_ComputerSettings);
lv_obj_set_width( ui_AuthStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AuthStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AuthStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_AuthStatus,"Status: Not Secured");
lv_label_set_recolor(ui_AuthStatus,"true");

ui_ComputerAuthPin = lv_textarea_create(ui_ComputerSettings);
lv_obj_set_width( ui_ComputerAuthPin, 200);
lv_obj_set_height( ui_ComputerAuthPin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ComputerAuthPin, -45 );
lv_obj_set_y( ui_ComputerAuthPin, 2 );
lv_obj_set_align( ui_ComputerAuthPin, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_ComputerAuthPin,4);
lv_textarea_set_placeholder_text(ui_ComputerAuthPin,"Pin");
lv_textarea_set_one_line(ui_ComputerAuthPin,true);
lv_textarea_set_password_mode(ui_ComputerAuthPin, true);
lv_obj_set_style_bg_color(ui_ComputerAuthPin, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ComputerAuthPin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ComputerAuthPinNew = lv_textarea_create(ui_ComputerSettings);
lv_obj_set_width( ui_ComputerAuthPinNew, 200);
lv_obj_set_height( ui_ComputerAuthPinNew, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ComputerAuthPinNew, -36 );
lv_obj_set_y( ui_ComputerAuthPinNew, -77 );
lv_obj_set_align( ui_ComputerAuthPinNew, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_ComputerAuthPinNew,4);
lv_textarea_set_placeholder_text(ui_ComputerAuthPinNew,"New pin");
lv_textarea_set_one_line(ui_ComputerAuthPinNew,true);
lv_textarea_set_password_mode(ui_ComputerAuthPinNew, true);
lv_obj_set_style_bg_color(ui_ComputerAuthPinNew, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ComputerAuthPinNew, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ComputerSaveButton = lv_btn_create(ui_ComputerSettings);
lv_obj_set_height( ui_ComputerSaveButton, 40);
lv_obj_set_width( ui_ComputerSaveButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_ComputerSaveButton, 261 );
lv_obj_set_y( ui_ComputerSaveButton, -52 );
lv_obj_set_align( ui_ComputerSaveButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ComputerSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ComputerSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ComputerSaveButton, lv_color_hex(0xE70004), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ComputerSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ComputerSaveText = lv_label_create(ui_ComputerSaveButton);
lv_obj_set_width( ui_ComputerSaveText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ComputerSaveText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ComputerSaveText, LV_ALIGN_CENTER );
lv_label_set_text(ui_ComputerSaveText,"Save");

ui_DeviceSettings = lv_obj_create(ui_SettingsPanel);
lv_obj_set_height( ui_DeviceSettings, lv_pct(100));
lv_obj_set_width( ui_DeviceSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_DeviceSettings, -19 );
lv_obj_set_y( ui_DeviceSettings, -433 );
lv_obj_set_align( ui_DeviceSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_DeviceSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_DeviceSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_DeviceSettings, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeviceSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_DeviceSettings, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeviceSettingsHeader = lv_label_create(ui_DeviceSettings);
lv_obj_set_width( ui_DeviceSettingsHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DeviceSettingsHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DeviceSettingsHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_DeviceSettingsHeader,"Device Settings:");
lv_obj_set_style_text_font(ui_DeviceSettingsHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_DeviceSettings);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Brightness");

ui_ScreenBrightnessArk = lv_arc_create(ui_DeviceSettings);
lv_obj_set_width( ui_ScreenBrightnessArk, 150);
lv_obj_set_height( ui_ScreenBrightnessArk, 150);
lv_obj_set_align( ui_ScreenBrightnessArk, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ScreenBrightnessArk, 10,100);
lv_obj_set_style_arc_color(ui_ScreenBrightnessArk, lv_color_hex(0x080C10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ScreenBrightnessArk, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ScreenBrightnessArk, lv_color_hex(0xE70004), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ScreenBrightnessArk, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ScreenBrightnessArk, lv_color_hex(0xE70004), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenBrightnessArk, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ScreenBrightnessArk, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenBrightnessArk, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ScreenBrightnessArk, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ScreenBrightnessArk, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ClockSettings = lv_obj_create(ui_SettingsPanel);
lv_obj_set_height( ui_ClockSettings, lv_pct(100));
lv_obj_set_width( ui_ClockSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ClockSettings, -19 );
lv_obj_set_y( ui_ClockSettings, -434 );
lv_obj_set_align( ui_ClockSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ClockSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ClockSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_ClockSettings, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ClockSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ClockSettings, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ClockSettingsHeader = lv_label_create(ui_ClockSettings);
lv_obj_set_width( ui_ClockSettingsHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ClockSettingsHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ClockSettingsHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_ClockSettingsHeader,"Clock Settings:");
lv_obj_set_style_text_font(ui_ClockSettingsHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ClockUtcSelected = lv_label_create(ui_ClockSettings);
lv_obj_set_width( ui_ClockUtcSelected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ClockUtcSelected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ClockUtcSelected, LV_ALIGN_CENTER );
lv_label_set_text(ui_ClockUtcSelected,"Selected Timezone:");

ui_ClockTimezoneRoller = lv_roller_create(ui_ClockSettings);
lv_roller_set_options( ui_ClockTimezoneRoller, "00:00\n+01:00\n+02:00\n+03:00\n+04:00\n+05:00\n+05:30\n+05:45\n+06:00\n+06:30\n+07:00\n+08:00\n+08:45\n+09:00\n+09:30\n+10:00\n+11:00\n+12:00\n+13:00\n+14:00\n-12:00\n-11:00\n-10:00\n-09:30\n-09:00\n-08:45\n-08:00\n-07:00\n-06:30\n-06:00\n-05:45\n-05:30\n-05:00\n-04:30\n-04:00\n-03:30\n-03:00\n-02:30\n-02:00\n-01:00\n-00:30", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_ClockTimezoneRoller, 200);
lv_obj_set_height( ui_ClockTimezoneRoller, lv_pct(50));
lv_obj_set_x( ui_ClockTimezoneRoller, 232 );
lv_obj_set_y( ui_ClockTimezoneRoller, -9 );
lv_obj_set_align( ui_ClockTimezoneRoller, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_ClockTimezoneRoller, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ClockTimezoneRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ClockTimezoneRoller, lv_color_hex(0xE70004), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ClockTimezoneRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ClockTimezoneSaveButton = lv_btn_create(ui_ClockSettings);
lv_obj_set_height( ui_ClockTimezoneSaveButton, 40);
lv_obj_set_width( ui_ClockTimezoneSaveButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_ClockTimezoneSaveButton, 262 );
lv_obj_set_y( ui_ClockTimezoneSaveButton, -52 );
lv_obj_set_align( ui_ClockTimezoneSaveButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ClockTimezoneSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ClockTimezoneSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ClockTimezoneSaveButton, lv_color_hex(0xE70004), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ClockTimezoneSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ComputerSaveText1 = lv_label_create(ui_ClockTimezoneSaveButton);
lv_obj_set_width( ui_ComputerSaveText1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ComputerSaveText1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ComputerSaveText1, LV_ALIGN_CENTER );
lv_label_set_text(ui_ComputerSaveText1,"Save");

ui_DeviceInformation = lv_obj_create(ui_SettingsPanel);
lv_obj_set_height( ui_DeviceInformation, lv_pct(100));
lv_obj_set_width( ui_DeviceInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_DeviceInformation, -19 );
lv_obj_set_y( ui_DeviceInformation, -433 );
lv_obj_set_align( ui_DeviceInformation, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_DeviceInformation,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_DeviceInformation, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_DeviceInformation, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeviceInformation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_DeviceInformation, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeviceInformationHeader = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_DeviceInformationHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DeviceInformationHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DeviceInformationHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_DeviceInformationHeader,"Information:");
lv_obj_set_style_text_font(ui_DeviceInformationHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KitsuDeckVersion = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_KitsuDeckVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KitsuDeckVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_KitsuDeckVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_KitsuDeckVersion,"Version: ");

ui_RamHeader = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_RamHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RamHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RamHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_RamHeader,"RAM:");

ui_RamValue = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_RamValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RamValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RamValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_RamValue,"");

ui_PsramHeader = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_PsramHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PsramHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PsramHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_PsramHeader,"PSRAM:");

ui_PsramValue = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_PsramValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PsramValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PsramValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_PsramValue,"");

ui_CreatedByInformation = lv_label_create(ui_DeviceInformation);
lv_obj_set_width( ui_CreatedByInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CreatedByInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CreatedByInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_CreatedByInformation,"Created by:\nKitsuneYokai");

ui_SettingsKeyboardText = lv_keyboard_create(ui_SettingsView);
lv_obj_set_width( ui_SettingsKeyboardText, lv_pct(100));
lv_obj_set_height( ui_SettingsKeyboardText, lv_pct(40));
lv_obj_set_x( ui_SettingsKeyboardText, 0 );
lv_obj_set_y( ui_SettingsKeyboardText, 145 );
lv_obj_set_align( ui_SettingsKeyboardText, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsKeyboardText, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SettingsKeyboardText, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_SettingsKeyboardText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsKeyboardText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsKeyboardText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsKeyboardText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsKeyboardNumber = lv_keyboard_create(ui_SettingsView);
lv_keyboard_set_mode(ui_SettingsKeyboardNumber,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_SettingsKeyboardNumber, lv_pct(100));
lv_obj_set_height( ui_SettingsKeyboardNumber, lv_pct(40));
lv_obj_set_x( ui_SettingsKeyboardNumber, 0 );
lv_obj_set_y( ui_SettingsKeyboardNumber, 145 );
lv_obj_set_align( ui_SettingsKeyboardNumber, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsKeyboardNumber, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SettingsKeyboardNumber, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_SettingsKeyboardNumber, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsKeyboardNumber, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsKeyboardNumber, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsKeyboardNumber, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SettingsBackToHome, ui_event_SettingsBackToHome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsHeaderPanel, ui_event_SettingsHeaderPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiPasswordTextInput, ui_event_WifiPasswordTextInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiScanButton, ui_event_WifiScanButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiSaveButton, ui_event_WifiSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TestWifiSettingsButton, ui_event_TestWifiSettingsButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiConnect, ui_event_WifiConnect, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ComputerAuthPin, ui_event_ComputerAuthPin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ComputerAuthPinNew, ui_event_ComputerAuthPinNew, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ComputerSaveButton, ui_event_ComputerSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ComputerSettings, ui_event_ComputerSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenBrightnessArk, ui_event_ScreenBrightnessArk, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DeviceSettings, ui_event_DeviceSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ClockTimezoneSaveButton, ui_event_ClockTimezoneSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ClockSettings, ui_event_ClockSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DeviceInformation, ui_event_DeviceInformation, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsPanel, ui_event_SettingsPanel, LV_EVENT_ALL, NULL);

}
